version: '2'

services:
  app:
    image: 'duzhinsky/yandex-mega-market:latest'
    build:
      context: docker
    container_name: app
    restart: always
    ports:
      - '80:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=QREExKXB8x9Lve
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=QREExKXB8x9Lve